### ISSUE TITLE
ImportError: cannot import name paths

### ISSUE THREAD

**Issue by 0815fox** [Rutzmoser/inkscape_dimensioning#10]
I just tried to use this extension but unfortunately I can't get it working.

In Inkscape 0.92 it fails with the following message:

```
Traceback (most recent call last):
  File "dimensioning.py", line 30, in <module>
    from inkex import paths
ImportError: cannot import name paths
```

I also tried it in 1.01, there it complains with the following message (which semms to be more likely an issue with executing python:

```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
```

... which tends to be a python 3 misconfiguration on my system.

Is the current version of this plugin meant to work on Inkscape 0.92 as well? If not it would be great to have it documented in the Readme...

By the way the path of the extension mentioned in the Readme seems to be different again, on my system its in "Dimensioning/Measurement" - not "create from path"
